// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/send-code": {
            "post": {
                "description": "Send verification code to email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Send verification code",
                "parameters": [
                    {
                        "description": "Email",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "email": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/verify-code": {
            "post": {
                "description": "Verify email with code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Verify code",
                "parameters": [
                    {
                        "description": "Email and code",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "code": {
                                    "type": "string"
                                },
                                "email": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "verified": {
                                    "type": "boolean"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/bookings": {
            "get": {
                "description": "Get booking history for a user by email",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Get user bookings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/theater-ticket-system_internal_models_responses.Booking"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new booking for selected seats. User will be created or found by email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Create booking",
                "parameters": [
                    {
                        "description": "Booking object",
                        "name": "booking",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "email": {
                                    "type": "string"
                                },
                                "name": {
                                    "type": "string"
                                },
                                "performance_id": {
                                    "type": "string"
                                },
                                "seat_ids": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/theater-ticket-system_internal_models_responses.Booking"
                        }
                    }
                }
            }
        },
        "/api/bookings/{id}": {
            "get": {
                "description": "Get detailed information about a booking",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Get booking by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Booking ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/theater-ticket-system_internal_models_responses.Booking"
                        }
                    }
                }
            }
        },
        "/api/bookings/{id}/cancel": {
            "patch": {
                "description": "Cancel an existing booking (only pending bookings can be cancelled)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Cancel booking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Booking ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/theater-ticket-system_internal_models_responses.Booking"
                        }
                    }
                }
            }
        },
        "/api/halls/{id}/seats": {
            "get": {
                "description": "Get static hall layout (not tied to a specific performance)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "seats"
                ],
                "summary": "Get hall seats",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hall ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/theater-ticket-system_internal_models_responses.Seat"
                            }
                        }
                    }
                }
            }
        },
        "/api/performances": {
            "get": {
                "description": "Get list of all performances with optional filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "performances"
                ],
                "summary": "Get all performances",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by play ID",
                        "name": "play_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by date from (RFC3339)",
                        "name": "date_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by date to (RFC3339)",
                        "name": "date_to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/theater-ticket-system_internal_models_responses.Performance"
                            }
                        }
                    }
                }
            }
        },
        "/api/performances/{id}": {
            "get": {
                "description": "Get detailed information about a performance",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "performances"
                ],
                "summary": "Get performance by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Performance ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/theater-ticket-system_internal_models_responses.Performance"
                        }
                    }
                }
            }
        },
        "/api/performances/{id}/seats": {
            "get": {
                "description": "Get hall layout with seat availability for a performance",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "performances"
                ],
                "summary": "Get performance seats",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Performance ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/theater-ticket-system_internal_models_responses.PerformanceSeat"
                            }
                        }
                    }
                }
            }
        },
        "/api/plays": {
            "get": {
                "description": "Get list of all plays",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plays"
                ],
                "summary": "Get all plays",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/theater-ticket-system_internal_models_responses.Play"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new play",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plays"
                ],
                "summary": "Create new play",
                "parameters": [
                    {
                        "description": "Play object",
                        "name": "play",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/theater-ticket-system_internal_models_requests.Play"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/theater-ticket-system_internal_models_responses.Play"
                        }
                    }
                }
            }
        },
        "/api/plays/{id}": {
            "get": {
                "description": "Get detailed information about a play",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plays"
                ],
                "summary": "Get play by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Play ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/theater-ticket-system_internal_models_responses.Play"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing play",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plays"
                ],
                "summary": "Update play",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Play ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Play object",
                        "name": "play",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/theater-ticket-system_internal_models_requests.Play"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/theater-ticket-system_internal_models_responses.Play"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a play",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plays"
                ],
                "summary": "Delete play",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Play ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }
    },
    "definitions": {
        "theater-ticket-system_internal_models_requests.Play": {
            "type": "object",
            "required": [
                "author",
                "description",
                "duration",
                "genre",
                "poster_url",
                "title"
            ],
            "properties": {
                "author": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "genre": {
                    "type": "string"
                },
                "poster_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "theater-ticket-system_internal_models_responses.Booking": {
            "type": "object",
            "required": [
                "created_at",
                "expires_at",
                "id",
                "performance_id",
                "status",
                "total_price",
                "updated_at",
                "user_id"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "performance": {
                    "$ref": "#/definitions/theater-ticket-system_internal_models_responses.Performance"
                },
                "performance_id": {
                    "type": "string"
                },
                "seats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/theater-ticket-system_internal_models_responses.PerformanceSeat"
                    }
                },
                "status": {
                    "description": "pending, confirmed, cancelled",
                    "type": "string"
                },
                "total_price": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "theater-ticket-system_internal_models_responses.Performance": {
            "type": "object",
            "required": [
                "created_at",
                "date",
                "id",
                "updated_at"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "play": {
                    "$ref": "#/definitions/theater-ticket-system_internal_models_responses.Play"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "scheduled",
                        "completed",
                        "cancelled"
                    ]
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "theater-ticket-system_internal_models_responses.PerformanceSeat": {
            "type": "object",
            "required": [
                "id",
                "performance_id",
                "price",
                "seat_id",
                "status"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "performance_id": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "seat": {
                    "$ref": "#/definitions/theater-ticket-system_internal_models_responses.Seat"
                },
                "seat_id": {
                    "type": "string"
                },
                "status": {
                    "description": "available, reserved, sold",
                    "type": "string"
                }
            }
        },
        "theater-ticket-system_internal_models_responses.Play": {
            "type": "object",
            "required": [
                "author",
                "created_at",
                "description",
                "duration",
                "genre",
                "id",
                "poster_url",
                "title",
                "updated_at"
            ],
            "properties": {
                "author": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "genre": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "performances": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/theater-ticket-system_internal_models_responses.Performance"
                    }
                },
                "poster_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "theater-ticket-system_internal_models_responses.Seat": {
            "type": "object",
            "required": [
                "category",
                "hall_id",
                "id",
                "number",
                "row"
            ],
            "properties": {
                "category": {
                    "description": "parterre, balcony, box",
                    "type": "string"
                },
                "hall_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "row": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
